import type { Metadata } from 'next';
import { avenir, cormorant_infant, manege, tenor_sans } from '@/fonts';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import './globals.css';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
    title: 'Детский клуб Давай поиграем',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body
                className={`${avenir.variable} ${manege.variable} ${cormorant_infant.variable} ${tenor_sans.variable} antialiased bg-lightbrown`}
            >
                <Header />
                <Toaster position="top-center" />
                {children}
                <Footer />
            </body>
        </html>
    );
}
