import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { avenir, cormorant_infant, manege, tenor_sans } from '@/fonts';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import CartProvider from '@/providers/CartProvider';
import './globals.css';

export const metadata: Metadata = {
    title: 'Детский клуб Давай поиграем',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body
                className={`${avenir.variable} ${manege.variable} ${cormorant_infant.variable} ${tenor_sans.variable} antialiased bg-lightbrown`}
                suppressHydrationWarning
            >
                <CartProvider>
                    <Header />
                    <Toaster position="top-center" />
                    {children}
                    <Footer />
                </CartProvider>
            </body>
        </html>
    );
}
